import { CardProps } from "./types/cardProps.types";
import { DetailsCardProps } from "./types/detailsCardProps.types";

export const DataList = [
    {
        id: 1,
        title: 'Ankara',
        design: 4,
        url: require('./../assets/images/showroom/s-1.jpg'),
        subTypes: [
            {

                title: 'Ankara Gowns',
                description: 'Beautifully crafted gowns perfect for traditional events.',
                timeFrame: '72hrs',
                price: 12000,
                availableColors: ['Red', 'Green', 'Yellow', 'Blue'],
                availableSizes: ['S', 'M', 'L', 'XL'],
                image: require('./../assets/images/showroom/s-1.jpg'),
            },
            {
                title: 'Ankara Tops',
                description: 'Stylish and trendy Ankara tops for casual outings.',
                timeFrame: '48hrs',
                price: 8000,
                availableColors: ['Orange', 'Purple'],
                availableSizes: ['M', 'L'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
            {
                title: 'Ankara Skirts',
                description: 'Elegant skirts for a bold statement.',
                timeFrame: '72hrs',
                price: 10000,
                availableColors: ['Black', 'Pink'],
                availableSizes: ['S', 'M', 'L'],
                image: require('./../assets/images/showroom/s-3.jpg'),
            },
            {
                title: 'Ankara Two-Piece',
                description: 'Matching Ankara sets for a complete look.',
                timeFrame: '96hrs',
                price: 15000,
                availableColors: ['Multicolor'],
                availableSizes: ['S', 'M', 'L'],
                image: require('./../assets/images/showroom/s-4.jpg'),
            },
        ],
    },
    {
        id: 2,
        title: 'Adire',
        design: 3,
        url: require('./../assets/images/showroom/s-2.jpg'),
        subTypes: [
            {
                title: 'Adire Maxi Dress',
                description: 'Flowing dresses with unique tie-dye designs.',
                timeFrame: '96hrs',
                price: 20000,
                availableColors: ['Blue', 'Indigo', 'Gray'],
                availableSizes: ['M', 'L', 'XL'],
                image: require('./../assets/images/showroom/s-5.jpg'),
            },
            {
                title: 'Adire Shirts',
                description: 'Casual shirts for men and women.',
                timeFrame: '72hrs',
                price: 12000,
                availableColors: ['Purple', 'Black'],
                availableSizes: ['M', 'L', 'XL'],
                image: require('./../assets/images/showroom/s-5.jpg'),
            },
            {
                title: 'Adire Wraps',
                description: 'Traditional wraps for all occasions.',
                timeFrame: '96hrs',
                price: 8000,
                availableColors: ['Green', 'White'],
                availableSizes: ['Free Size'],
                image: require('./../assets/images/showroom/s-7.jpg'),
            },
        ],
    },
    {
        id: 3,
        title: 'Agbada',
        design: 2,
        url: require('./../assets/images/showroom/s-3.jpg'),
        subTypes: [
            {
                title: 'Classic Agbada',
                description: 'Elegant agbada designs for men.',
                timeFrame: '120hrs',
                price: 50000,
                availableColors: ['White', 'Gold', 'Black'],
                availableSizes: ['L', 'XL', 'XXL'],
                image: require('./../assets/images/showroom/s-5.jpg'),
            },
            {
                title: 'Modern Agbada',
                description: 'Trendy agbada designs with a modern touch.',
                timeFrame: '120hrs',
                price: 55000,
                availableColors: ['Gray', 'Navy Blue'],
                availableSizes: ['L', 'XL'],
                image: require('./../assets/images/showroom/s-9.jpg'),
            },
        ],
    },
    {
        id: 4,
        title: 'Two-Piece Sets',
        design: 3,
        url: require('./../assets/images/showroom/s-4.jpg'),
        subTypes: [
            {
                title: 'Corporate Two-Piece',
                description: 'Stylish sets for office and meetings.',
                timeFrame: '72hrs',
                price: 18000,
                availableColors: ['Black', 'Brown'],
                availableSizes: ['S', 'M', 'L'],
                image: require('./../assets/images/showroom/s-10.jpg'),
            },
            {
                title: 'Casual Two-Piece',
                description: 'Relaxed and comfortable sets for weekends.',
                timeFrame: '48hrs',
                price: 15000,
                availableColors: ['Blue', 'Green'],
                availableSizes: ['M', 'L'],
                image: require('./../assets/images/showroom/s-1.jpg'),
            },
            {
                title: 'Luxury Two-Piece',
                description: 'Premium fabrics and designs for special occasions.',
                timeFrame: '96hrs',
                price: 25000,
                availableColors: ['White', 'Gold'],
                availableSizes: ['M', 'L'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
        ],
    },
    {
        id: 5,
        title: 'Jeans',
        design: 4,
        url: require('./../assets/images/showroom/s-5.jpg'),
        subTypes: [
            {
                title: 'Skinny Jeans',
                description: 'Modern and trendy jeans for all occasions.',
                timeFrame: '48hrs',
                price: 12000,
                availableColors: ['Black', 'Blue'],
                availableSizes: ['28', '30', '32', '34'],
                image: require('./../assets/images/showroom/s-1.jpg'),
            },
            {
                title: 'Straight-Leg Jeans',
                description: 'Classic denim for a timeless look.',
                timeFrame: '72hrs',
                price: 15000,
                availableColors: ['Dark Blue', 'Gray'],
                availableSizes: ['30', '32', '34'],
                image: require('./../assets/images/showroom/s-4.jpg'),
            },
            {
                title: 'Boyfriend Jeans',
                description: 'Relaxed fit for a casual style.',
                timeFrame: '48hrs',
                price: 13000,
                availableColors: ['Light Blue', 'Black'],
                availableSizes: ['28', '30', '32'],
                image: require('./../assets/images/showroom/s-5.jpg'),
            },
            {
                title: 'Ripped Jeans',
                description: 'Edgy and trendy styles for fashion lovers.',
                timeFrame: '72hrs',
                price: 16000,
                availableColors: ['Blue', 'Black'],
                availableSizes: ['28', '30', '32'],
                image: require('./../assets/images/showroom/s-1.jpg'),
            },
        ],
    },
    {
        id: 6,
        title: 'Native Wears',
        design: 5,
        url: require('./../assets/images/showroom/s-6.jpg'),
        subTypes: [
            {
                title: 'Senator Style',
                description: 'Elegant and stylish native attire for men.',
                timeFrame: '96hrs',
                price: 25000,
                availableColors: ['Black', 'Gray', 'Blue'],
                availableSizes: ['M', 'L', 'XL'],
                image: require('./../assets/images/showroom/s-7.jpg'),
            },
            {
                title: 'Kaftan',
                description: 'Comfortable and classy kaftans for casual or formal wear.',
                timeFrame: '72hrs',
                price: 20000,
                availableColors: ['White', 'Gold', 'Brown'],
                availableSizes: ['M', 'L', 'XL', 'XXL'],
                image: require('./../assets/images/showroom/s-5.jpg'),
            },
            {
                title: 'Buba and Sokoto',
                description: 'Traditional attire with a modern twist.',
                timeFrame: '120hrs',
                price: 30000,
                availableColors: ['Green', 'Yellow', 'Black'],
                availableSizes: ['L', 'XL'],
                image: require('./../assets/images/showroom/s-9.jpg'),
            },
            {
                title: 'Native Gowns',
                description: 'Beautiful native gowns for women.',
                timeFrame: '96hrs',
                price: 25000,
                availableColors: ['Purple', 'Red'],
                availableSizes: ['S', 'M', 'L'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
            {
                title: 'Traditional Wraps',
                description: 'Versatile wraps for all occasions.',
                timeFrame: '72hrs',
                price: 15000,
                availableColors: ['Multicolor'],
                availableSizes: ['Free Size'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
        ],
    },
    {
        id: 7,
        title: 'Casual Wears',
        design: 4,
        url: require('./../assets/images/showroom/s-7.jpg'),
        subTypes: [
            {
                title: 'T-Shirts',
                description: 'Comfortable and stylish t-shirts for everyday use.',
                timeFrame: '48hrs',
                price: 7000,
                availableColors: ['White', 'Black', 'Gray'],
                availableSizes: ['S', 'M', 'L', 'XL'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
            {
                title: 'Shorts',
                description: 'Relaxed and trendy shorts for casual outings.',
                timeFrame: '48hrs',
                price: 6000,
                availableColors: ['Blue', 'Beige'],
                availableSizes: ['M', 'L', 'XL'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
            {
                title: 'Joggers',
                description: 'Comfy joggers perfect for workouts or lounging.',
                timeFrame: '48hrs',
                price: 9000,
                availableColors: ['Gray', 'Black', 'Navy'],
                availableSizes: ['M', 'L', 'XL'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
            {
                title: 'Hoodies',
                description: 'Cozy hoodies for a relaxed vibe.',
                timeFrame: '72hrs',
                price: 12000,
                availableColors: ['Black', 'Green', 'Red'],
                availableSizes: ['M', 'L', 'XL'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
        ],
    },
    {
        id: 8,
        title: 'Dresses',
        design: 3,
        url: require('./../assets/images/showroom/s-3.jpg'),
        subTypes: [
            {
                title: 'Evening Gowns',
                description: 'Elegant gowns for special occasions.',
                timeFrame: '96hrs',
                price: 35000,
                availableColors: ['Red', 'Navy Blue', 'Black'],
                availableSizes: ['M', 'L'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
            {
                title: 'Casual Dresses',
                description: 'Comfortable dresses for day-to-day activities.',
                timeFrame: '72hrs',
                price: 15000,
                availableColors: ['Yellow', 'Pink', 'White'],
                availableSizes: ['S', 'M', 'L'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
            {
                title: 'Formal Dresses',
                description: 'Sophisticated dresses for corporate events.',
                timeFrame: '120hrs',
                price: 25000,
                availableColors: ['Black', 'Gray'],
                availableSizes: ['M', 'L', 'XL'],
                image: require('./../assets/images/showroom/s-2.jpg'),
            },
        ],
    },

];
